Codebrahma/gatsby-ecommerce-pwa

src/components/presentational/filters/FilterBy.js, src/components/presentational/filters/filter.scss, src/components/presentational/products/SideBarItem.js, src/pages/furniture.js, src/pages/men.js, src/pages/women.js
Small screen UI is implemented with invisible checkbox group.
Filter borders will highlight on select as check boxes are invisible.
Please Review
=> Filters small screen UI implemented

package-lock.json, src/components/css/custom.scss
PT Sans css import bug fix in custom.scss.
Please review
=> CSS Bug  fix

src/components/css/cartStyle.scss, src/components/presentational/CartContainer.js, src/components/presentational/CartItems.js, src/components/presentational/CartSummary.js, src/pages/cart.js
Cart page implemented with few default products.
please review
=> Cart page Implementation

src/layouts/Navbar.js, src/layouts/index.scss
Active state added to navbar links
Please Review
=> Navbar link active state style added

package-lock.json, src/components/css/animate.scss, src/components/css/productCard.scss, src/components/menu.js, src/layouts/NavbarMobile.js, src/layouts/header.js, src/layouts/index.js, src/layouts/index.scss, src/pages/index.js, src/pages/productItem.js, src/pages/style.scss
navbar hover effect,
image resizing,
Product page spacing
---Fixed.
Please review
=> Style fixes

src/components/menu.js, src/layouts/index.scss
small screen nav item stacking.
--Fixed
Please review
=> NavItems minor bug fix

package-lock.json, package.json, src/components/presentational/CartContainer.js, src/components/presentational/CartItems.js, src/components/presentational/CartSummary.js, src/pages/cart.js, src/pages/style.scss
Loading icon added.
Update button styled.
Please review
=> Style fixes Cart page

src/pages/style.scss
Update Cart button responsive on small screen.
Please review
=> Update cart button resposiveness fix

src/components/presentational/CartSummary.js, src/components/presentational/CheckoutInfo.js, src/components/presentational/FormInputField.js, src/pages/order.js, src/pages/style.scss
Checkout page Implemented with default data.
Please review
=> Checkout page UI implementation

src/components/presentational/CartContainer.js, src/components/presentational/CartItems.js, src/components/presentational/CartSummary.js, src/components/presentational/products/ProductList.js, src/components/presentational/products/SideBarItem.js, src/components/presentational/products/productCard.js, src/pages/boys.js, src/pages/productItem.js, src/pages/style.scss, src/pages/women.js
1) Home page shop now button centered on small screen
2) Already in cart modified to IN CART in cart page
3) Warnings from home page till cart page fixed.
Please review
=> Major bug fixes

src/components/DemoProductCard.js, src/components/DemoProductList.js, src/components/demo-products-list.scss, src/pages/demoProductItem.js, src/pages/weightloss.js
=> Product list page implemented

src/components/DemoCorouselItem.js, src/components/DemoProductCard.js, src/components/DemoProductVariants.js, src/components/DemoVariantItem.js, src/components/demo-products-list.scss, src/pages/demo-home.scss, src/pages/demo-products.scss, src/pages/demoProductItem.js, src/pages/index.js
1. Home page carousel width adjusted
2. Product subscription steps css fixed
3. Added active state to variants in productItem page
=> Css bug fixes

gatsby-node.js, src/layouts/Menu.js, src/layouts/Navbar.js, src/layouts/NavbarMobile.js, src/layouts/index.js, src/layouts/style.scss, src/pages/home.scss
fix sidebar toggle. 
css changes. 
add close button to pwa install popup.
=> minor fixes and improvements

.gitignore, README.md
=> Updated README.md to with env instructions

src/components/TakeMoney.js, src/components/form.js, src/pages/checkout.js
checkout page form field enabled and build error fix
=> Checkout page fixes

src/pages/ProductItem.js, src/pages/cart.js, src/pages/checkout.js
remove old code and add tofixed method for handling display amount on some products
=> remove garbage code and add tofixed on diplaying amount

src/pages/home.scss
carousel style bug on firefox fixed
=> carousel on firefox bug fixed

.circleci/config.yml
added circle ci with lint config
=> circle CI config.yml added

package-lock.json, package.json, src/templates/Product.js, src/templates/product/VariantItem.js, src/templates/product/product.scss
Product page styled with Rebass
=> Product Item page styled with Rebass

src/templates/Product.js, src/templates/product/ProductFaqs.js, src/templates/product/ProductSubscription.js
=> Minor text styling fix

gatsby-node.js, src/components/Payment.js, src/pages/cart.js, src/pages/checkout.js, src/pages/index.js, src/templates/Category.js, src/templates/Product.js, theme-path.js, themes/default-theme/components/CarouselButton.js, themes/default-theme/components/CheckoutDetails.js, themes/default-theme/components/ProductCard.js, themes/default-theme/components/ProductList.js, themes/default-theme/themeComponents/Cart.js, themes/default-theme/themeComponents/CategoryList.js, themes/default-theme/themeComponents/CheckoutPage.js, themes/default-theme/themeComponents/HomePage.js, themes/default-theme/themeComponents/ProductPage.js
=> Themeable lint fixes

.circleci/config.yml, themes/default-theme/components/CarouselButton.js
Caching config added for circle CI
=> caching config added for circleCI, Carousel Button style fixed

gatsby-config.js, package-lock.json, package.json, themes/default-theme/package.json, yarn.lock
Added gatsby-plugin-styled-components
Css breaking fixed
=> Css breaking fix
